// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plcyhxyquhdvrozikiss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsY3loeHlxdWhkdnJvemlraXNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NTYwNzQsImV4cCI6MjA2NTQzMjA3NH0.ji0UvCWneGtJ7mRVTddOw8ynhlHyEkHX2LKPMCOKQ28";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);